name: docs

on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize, repoened, edited]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
      
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        key: ${{ runner.os }}-pip-${{ hashFiles('./requirements/requirements.txt') }}-${{ hashFiles('**/docs.txt') }}-${{ hashFiles('**/test.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -r ./requirements/requirements.txt
        pip install -r ./requirements/docs.txt
        pip install -r ./requirements/test.txt

    - name: Run docstr coverage
      run: |
        mkdir documentation-reports
        docstr-coverage discoreddit --verbose=3 --exclude=tests --skipinit 2>&1 | tee ./documentation-reports/docstr-coverage.txt
    
    - name: Run pydocstyle
      run: |
        (pydocstyle discoreddit 2>&1 | tee ./documentation-reports/pydocstyle-coverage.txt; exit ${PIPESTATUS[0]})

    - name: Upload documentation reports as artifact
      uses: actions/upload-artifact@v2
      with:
        name: documentation-reports
        path: ./documentation-reports/